package com.Os4ed.Modules;

import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.Select;

import com.Os4ed.Pages.CreateHomePage;
import com.Os4ed.Pages.CreateSchoolSetupPage;
import com.Os4ed.Test.SelTestCase;
import com.Os4ed.Utils.Log;

public class SchoolSetupPageAction extends SelTestCase {
	
	public static void executeEventsOnSchoolSetupPage() throws InterruptedException {
		Log.info("Events Going to Performed on School Setup Page ");
		// Clicking on  School Setup Tab
		driver.switchTo().frame("body");
		CreateHomePage.HomePageDetails.schoolSetupLink.click();
		Thread.sleep(2000);
		Log.info("Clicking on School Setup Tab");
		
		CreateSchoolSetupPage.SchoolSetupPageDetails.calendars.click();
		Thread.sleep(1000);
		Log.info("Clicking on Calendar Link");
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.createNewCalendar.click();
		Thread.sleep(1000);
		Log.info("Clicking on New Calendar Link");
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.titleTextBox.clear();
		Thread.sleep(1000);
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.titleTextBox.sendKeys("Test Calendar");
		Thread.sleep(1000);
		Log.info("Entering the Calendar Name");
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.defaultCalendarCheckBox.click();
		Thread.sleep(1000);
		Log.info("Clicking on Default Checkbox");
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.superAdminCheckBox.click();
		Thread.sleep(1000);
		Log.info("Clicking on Super Admin Checkbox");
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.adminCheckBox.click();
		Thread.sleep(1000);
		Log.info("Clicking on Admin Checkbox");
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.teacherCheckBox.click();
		Thread.sleep(1000);
		Log.info("Clicking on Teacher Checkbox");
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.studentCheckBox.click();
		Thread.sleep(1000);
		Log.info("Clicking on Student Checkbox");
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.parentCheckBox.click();
		Thread.sleep(1000);
		Log.info("Clicking on Parent Checkbox");
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.okButton.click();
		Thread.sleep(1000);
		Log.info("Clicking on Ok Button");
		
		
		CreateSchoolSetupPage.SchoolSetupPageDetails.markingPeriods.click();
		Thread.sleep(1000);
		Log.info("Clicking on Marking Period Link");
		//Semester 1
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.addButtonSem1.click();
		Thread.sleep(1000);
		Log.info("Clicking on Add Button for Semester 1");
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.titleTextBoxS1.clear();
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.titleTextBoxS1.sendKeys("Semester 1");
		Log.info("Entering the Semester1 Name");
		Thread.sleep(1000);
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.shortNameTextBoxS1.clear();
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.shortNameTextBoxS1.sendKeys("Sem 1");
		Thread.sleep(1000);
		Log.info("Entering Semester1 Short Name");
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.sortOrderTextBoxS1.sendKeys("1");
		Thread.sleep(1000);
		Log.info("Entering Semester1 Sort Order");
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.beginsCalendarS1.click();
		Thread.sleep(1000);
		Log.info("Clicking on Semester1 Begins Calendar");
		WebElement beginYearS1 = CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.selectBeginsCalendarYearS1;
		Select selectBeginYearS1 = new Select(beginYearS1);
		selectBeginYearS1.selectByValue("2016");
		Thread.sleep(1000);
	 	WebElement beginMonthS1 = CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.selectBeginsCalendarMonthS1;
	 	Select selectBeginMonthS1 = new Select(beginMonthS1);
	 	selectBeginMonthS1.selectByValue("0");
	 	Thread.sleep(1000);
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.selectBeginsCalendarDayS1.click();
	 	Thread.sleep(1000);
	 	Log.info("Entering Begins Date for Semester1");
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.endsCalendarS1.click();
	 	Thread.sleep(1000);
	 	Log.info("Clicking on Semester1 Ends Calendar");
	 	WebElement endYearS1 = CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.selectEndsCalendarYearS1;
		Select selectEndYearS1 = new Select(endYearS1);
		selectEndYearS1.selectByValue("2016");
		Thread.sleep(1000);
	 	WebElement endMonthS1 = CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.selectEndsCalendarMonthS1;
	 	Select selectEndMonthS1 = new Select(endMonthS1);
	 	selectEndMonthS1.selectByValue("5");
	 	Thread.sleep(1000);
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.selectEndsCalendarDayS1.click();
	 	Thread.sleep(1000);
	 	Log.info("Entering Ends Date for Semester 1");
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.saveButtonS1.click();
	 	Thread.sleep(1000);
	 	Log.info("Clicking on Save Button for Semester1");
	 	//Semester 2
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.addButtonSem2.click();
	 	Thread.sleep(1000);
	 	Log.info("Clicking on Add Button for Semester 2");
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.titleTextBoxS2.clear();
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.titleTextBoxS2.sendKeys("Semester 2");
	 	Thread.sleep(1000);
	 	Log.info("Entering the Semester2 Name");
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.shortNameTextBoxS2.clear();
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.shortNameTextBoxS2.sendKeys("Sem 2");
	 	Thread.sleep(1000);
	 	Log.info("Entering the Semester2 Short Name");
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.sortOrderTextBoxS2.sendKeys("2");
	 	Thread.sleep(1000);
	 	Log.info("Entering Semester2 Sort Order");
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.beginsCalendarS2.click();
	 	Thread.sleep(1000);
	 	Log.info("Clicking on Semester2 Begins Calendar");
	 	WebElement beginYearS2 = CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.selectBeginsCalendarYearS2;
		Select selectBeginYearS2 = new Select(beginYearS2);
		selectBeginYearS2.selectByValue("2016");
		Thread.sleep(1000);
		WebElement beginMonthS2 = CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.selectBeginsCalendarMonthS2;
	 	Select selectBeginMonthS2 = new Select(beginMonthS2);
	 	selectBeginMonthS2.selectByValue("6");
	 	Thread.sleep(1000);
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.selectBeginsCalendarDayS2.click();
	 	Thread.sleep(1000);
	 	Log.info("Entering Begins Date for Semester2");
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.endsCalendarS2.click();
	 	Thread.sleep(1000);
	 	Log.info("Clicking on Semester2 Ends Calendar");
	 	WebElement endYearS2 = CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.selectEndsCalendarYearS2;
		Select selectEndYearS2 = new Select(endYearS2);
		selectEndYearS2.selectByValue("2016");
		Thread.sleep(1000);
		WebElement endMonthS2 = CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.selectEndsCalendarMonthS1;
	 	Select selectEndMonthS2 = new Select(endMonthS2);
	 	selectEndMonthS2.selectByValue("11");
	 	Thread.sleep(1000);
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.selectEndsCalendarDayS2.click();
	 	Thread.sleep(1000);
	 	Log.info("Entering Ends Date for Semester2");
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.saveButtonS2.click();
	 	Thread.sleep(1000);
	 	Log.info("Clicking on Save Button for Semester2");
	 	
	 	
	 	//Quarter 1
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.linkSemester1.click();
	 	Thread.sleep(1000);
	 	Log.info("Clicking on Semester1 Link");
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.addButtonQuar1.click();
	 	Thread.sleep(1000);
	 	Log.info("Clicking on Add Button for Quarter1");
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.titleTextBoxQ1.clear();
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.titleTextBoxQ1.sendKeys("Quarter 1");
	 	Thread.sleep(1000);
	 	Log.info("Entering Quarter1 Name");
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.shortNameTextBoxQ1.clear();
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.shortNameTextBoxQ1.sendKeys("Q1");
	 	Thread.sleep(1000);
	 	Log.info("Entering Quarter1 Short Name");
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.sortOrderTextBoxQ1.sendKeys("1");
	 	Thread.sleep(1000);
	 	Log.info("Entering Quarter1 Sort Order");
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.beginsCalendarQ1.click();
	 	Thread.sleep(1000);
	 	Log.info("Clicking on Quarter1 Begins Calendar");
	 	WebElement beginYearQ1 = CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.selectBeginsCalendarYearQ1;
		Select selectBeginYearQ1 = new Select(beginYearQ1);
		selectBeginYearQ1.selectByValue("2016");
		Thread.sleep(1000);
		WebElement beginMonthSQ1 = CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.selectBeginsCalendarMonthQ1;
	 	Select selectBeginMonthQ1 = new Select(beginMonthSQ1);
	 	selectBeginMonthQ1.selectByValue("0");
	 	Thread.sleep(1000);
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.selectBeginsCalendarDayQ1.click();
	 	Thread.sleep(1000);
	 	Log.info("Entering Begins date for Quarter1");
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.endCalendarQ1.click();
	 	Thread.sleep(1000);
	 	Log.info("Clicking on Quarter1 Ends Calendar");
	 	WebElement endYearQ1 = CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.selectEndsCalendarYearQ1;
		Select selectEndYearQ1 = new Select(endYearQ1);
		selectEndYearQ1.selectByValue("2016");
		Thread.sleep(1000);
		WebElement endMonthQ1 = CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.selectEndsCalendarMonthQ1;
	 	Select selectEndMonthQ1 = new Select(endMonthQ1);
	 	selectEndMonthQ1.selectByValue("2");
	 	Thread.sleep(1000);
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.selectEndsCalendarDayQ1.click();
	 	Thread.sleep(1000);
	 	Log.info("Entering Ends Date for Quarter1");
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.saveButtonQ1.click();
	 	Thread.sleep(1000);
	 	Log.info("Clicking on Save Button for Quarter1");
	 	
	 	//Quarter 2
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.addButtonQuar2.click();
	 	Thread.sleep(1000);
	 	Log.info("Clicking on Add Button for Quarter2");
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.titleTextBoxQ2.clear();
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.titleTextBoxQ2.sendKeys("Quarter 2");
	 	Thread.sleep(1000);
	 	Log.info("Entering Quarter2 Name");
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.shortNameTextBoxQ2.clear();
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.shortNameTextBoxQ2.sendKeys("Q2");
	 	Thread.sleep(1000);
	 	Log.info("Entering Quarter2 Short Name");
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.sortOrderTextBoxQ2.sendKeys("2");
	 	Thread.sleep(1000);
	 	Log.info("Entering Quarter2 Sort Order");
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.beginsCalendarQ2.click();
	 	Thread.sleep(1000);
	 	Log.info("Clicking on Quarter2 Begins Calendar");
	 	WebElement beginYearQ2 = CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.selectBeginsCalendarYearQ2;
		Select selectBeginYearQ2 = new Select(beginYearQ2);
		selectBeginYearQ2.selectByValue("2016");
		Thread.sleep(1000);
		WebElement beginMonthSQ2 = CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.selectBeginsCalendarMonthQ2;
	 	Select selectBeginMonthQ2 = new Select(beginMonthSQ2);
	 	selectBeginMonthQ2.selectByValue("3");
	 	Thread.sleep(1000);
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.selectBeginsCalendarDayQ1.click();
	 	Thread.sleep(1000);
	 	Log.info("Entering Begins Date for Quarter2");
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.endCalendarQ2.click();
	 	Thread.sleep(1000);
	 	Log.info("Clicking on Quarter2 Ends Calendar");
	 	WebElement endYearQ2 = CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.selectEndsCalendarYearQ2;
		Select selectEndYearQ2 = new Select(endYearQ2);
		selectEndYearQ2.selectByValue("2016");
		Thread.sleep(1000);
		WebElement endMonthQ2 = CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.selectEndsCalendarMonthQ2;
	 	Select selectEndMonthQ2 = new Select(endMonthQ2);
	 	selectEndMonthQ2.selectByValue("5");
	 	Thread.sleep(1000);
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.selectEndsCalendarDayQ2.click();
	 	Thread.sleep(1000);
	 	Log.info("Entering Ends Date for Quarter2");
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.saveButtonQ2.click();
	 	Thread.sleep(1000);
	 	Log.info("Clicking on Save Button for Quarter2");
	 	
	 	//Quarter 3
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.linkSemester2.click();
	 	Thread.sleep(1000);
	 	Log.info("Clicking on Semester2 Link");
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.addButtonQuar3.click();
	 	Thread.sleep(1000);
	 	Log.info("Clicking on Add Button for Quarter3");
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.titleTextBoxQ3.clear();
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.titleTextBoxQ3.sendKeys("Quarter 3");
	 	Thread.sleep(1000);
	 	Log.info("Entering the Quarter3 Name");
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.shortNameTextBoxQ3.clear();
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.shortNameTextBoxQ3.sendKeys("Q3");
	 	Thread.sleep(1000);
	 	Log.info("Entering the Quarter3 Short Name");
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.sortOrderTextBoxQ3.sendKeys("3");
	 	Thread.sleep(1000);
	 	Log.info("Entering Quarter3 Sort Order");
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.beginsCalendarQ3.click();
	 	Thread.sleep(1000);
	 	Log.info("Clicking on Quarter3 Begins Calendar");
	 	WebElement beginYearQ3 = CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.selectBeginsCalendarYearQ3;
		Select selectBeginYearQ3 = new Select(beginYearQ3);
		selectBeginYearQ3.selectByValue("2016");
		Thread.sleep(1000);
		WebElement beginMonthSQ3 = CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.selectBeginsCalendarMonthQ3;
	 	Select selectBeginMonthQ3 = new Select(beginMonthSQ3);
	 	selectBeginMonthQ3.selectByValue("6");
	 	Thread.sleep(1000);
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.selectBeginsCalendarDayQ3.click();
	 	Thread.sleep(1000);
	 	Log.info("Entering Begins Date for Quarter3");
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.endCalendarQ3.click();
	 	Thread.sleep(1000);
	 	Log.info("Clicking on Quarter3 Ends Calendar");
	 	WebElement endYearQ3 = CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.selectEndsCalendarYearQ3;
		Select selectEndYearQ3 = new Select(endYearQ3);
		selectEndYearQ3.selectByValue("2016");
		Thread.sleep(1000);
		WebElement endMonthQ3 = CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.selectEndsCalendarMonthQ3;
	 	Select selectEndMonthQ3 = new Select(endMonthQ3);
	 	selectEndMonthQ3.selectByValue("8");
	 	Thread.sleep(1000);
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.selectEndsCalendarDayQ3.click();
	 	Thread.sleep(1000);
	 	Log.info("Entering Ends Date for Quarter3");
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.saveButtonQ3.click();
	 	Thread.sleep(1000);
	 	Log.info("Clicking on Save Button for Quarter3");
	 	
	 	//Quarter 4
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.addButtonQuar4.click();
	 	Thread.sleep(1000);
	 	Log.info("Clicking on Add Button for Quarter4");
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.titleTextBoxQ4.clear();
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.titleTextBoxQ4.sendKeys("Quarter 4");
	 	Thread.sleep(1000);
	 	Log.info("Entering the Quarter4 Name");
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.shortNameTextBoxQ4.clear();
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.shortNameTextBoxQ4.sendKeys("Q4");
	 	Thread.sleep(1000);
	 	Log.info("Entering the Quarter4 Short Name");
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.sortOrderTextBoxQ4.sendKeys("4");
	 	Thread.sleep(1000);
	 	Log.info("Entering the Quarter4 Sort Order");
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.beginsCalendarQ4.click();
	 	Thread.sleep(1000);
	 	Log.info("Clicking on Quarter4 Begins Calendar");
	 	WebElement beginYearQ4 = CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.selectBeginsCalendarYearQ4;
		Select selectBeginYearQ4 = new Select(beginYearQ4);
		selectBeginYearQ4.selectByValue("2016");
		Thread.sleep(1000);
		WebElement beginMonthSQ4 = CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.selectBeginsCalendarMonthQ4;
	 	Select selectBeginMonthQ4 = new Select(beginMonthSQ4);
	 	selectBeginMonthQ4.selectByValue("9");
	 	Thread.sleep(1000);
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.selectBeginsCalendarDayQ4.click();
	 	Thread.sleep(1000);
	 	Log.info("Entering Begins Date for Quarter4");
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.endCalendarQ2.click();
	 	Thread.sleep(1000);
	 	Log.info("Clicking on Quarter4 Ends Calendar");
	 	WebElement endYearQ4 = CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.selectEndsCalendarYearQ4;
		Select selectEndYearQ4 = new Select(endYearQ4);
		selectEndYearQ4.selectByValue("2016");
		Thread.sleep(1000);
		WebElement endMonthQ4 = CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.selectEndsCalendarMonthQ4;
	 	Select selectEndMonthQ4 = new Select(endMonthQ4);
	 	selectEndMonthQ4.selectByValue("11");
	 	Thread.sleep(1000);
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.selectEndsCalendarDayQ4.click();
	 	Thread.sleep(1000);
	 	Log.info("Entering Ends Date for Quarter4");
	 	CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.saveButtonQ4.click();
	 	Thread.sleep(1000);
	 	Log.info("Clicking on Save Button for Quarter4");
	 	
	 	//Rooms
		
		CreateSchoolSetupPage.SchoolSetupPageDetails.rooms.click();
		Thread.sleep(1000);
		Log.info("Clicking on Rooms Link");
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.titleRoom1TextBox.clear();
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.titleRoom1TextBox.sendKeys("Room 1");
		Thread.sleep(1000);
		Log.info("Entering Room1 Name");
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.capacityRoom1TextBox.clear();
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.capacityRoom1TextBox.sendKeys("100");
		Thread.sleep(1000);
		Log.info("Entering Room1 Capacity");
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.sortOrderRoom1TextBox.sendKeys("1");
		Thread.sleep(1000);
		Log.info("Entering Room1 Sort Order");
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.saveButtonRoom1.click();
		Thread.sleep(1000);
		Log.info("Clicking on Save Button for Room1");
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.titleRoom2TextBox.clear();
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.titleRoom2TextBox.sendKeys("Room 2");
		Thread.sleep(1000);
		Log.info("Entering Room2 Name");
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.capacityRoom2TextBox.clear();
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.capacityRoom2TextBox.sendKeys("150");
		Thread.sleep(1000);
		Log.info("Entering Room2 Capacity");
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.sortOrderRoom2TextBox.sendKeys("2");
		Thread.sleep(1000);
		Log.info("Entering Room2 Sort Order");
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.saveButtonRoom2.click();
		Thread.sleep(1000);
		Log.info("Clicking on Save Button for Room2");
		
		//Periods
		
		CreateSchoolSetupPage.SchoolSetupPageDetails.periods.click();
		Thread.sleep(1000);
		Log.info("Clicking on Periods Link");
		//Period 1
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.PeriodPageDetails.titlePeriod1.clear();
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.PeriodPageDetails.titlePeriod1.sendKeys("Period 1");
		Thread.sleep(1000);
		Log.info("Entering Period1 Name");
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.PeriodPageDetails.shortNamePeriod1.clear();
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.PeriodPageDetails.shortNamePeriod1.sendKeys("P1");
		Thread.sleep(1000);
		Log.info("Entering Period1 Short Name");
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.PeriodPageDetails.sortOrderPeriod1.sendKeys("1");
		Thread.sleep(1000);
		Log.info("Entering Period1 Sort Order");
		WebElement startP1Hour = CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.PeriodPageDetails.startHourPeriod1;
		Select selectstartP1Hour = new Select(startP1Hour);
		selectstartP1Hour.selectByValue("9");
		Thread.sleep(1000);
		WebElement startP1Min = CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.PeriodPageDetails.startMinutePeriod1;
		Select selectstartP1Min = new Select(startP1Min);
		selectstartP1Min.selectByValue("0");
		Thread.sleep(1000);
		WebElement startP1Sec = CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.PeriodPageDetails.startSecondPeriod1;
		Select selectstartP1Sec = new Select(startP1Sec);
		selectstartP1Sec.selectByValue("AM");
		Thread.sleep(1000);
		Log.info("Entering Period1 Start Time");
		WebElement endP1Hour = CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.PeriodPageDetails.endHourPeriod1;
		Select selectendP1Hour = new Select(endP1Hour);
		selectendP1Hour.selectByValue("9");
		Thread.sleep(1000);
		WebElement endP1Min = CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.PeriodPageDetails.endMinutePeriod1;
		Select selectendP1Min = new Select(endP1Min);
		selectendP1Min.selectByValue("30");
		Thread.sleep(1000);
		WebElement endP1Sec = CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.PeriodPageDetails.endSecondPeriod1;
		Select selectendP1Sec = new Select(endP1Sec);
		selectendP1Sec.selectByValue("AM");
		Thread.sleep(1000);
		Log.info("Entering Period1 End Time");
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.PeriodPageDetails.usedForAttendancePeriod1.click();
		Thread.sleep(1000);
		Log.info("Clicking on Used For Attendance Checkbox for Period1");
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.PeriodPageDetails.ignoreForSchedulingPeriod1.click();
		Thread.sleep(1000);
		Log.info("Clicking on Ignore For Scheduling for Period1");
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.PeriodPageDetails.saveButtonPeriod1.click();
		Thread.sleep(1000);
		Log.info("Clicking on Save Button for Period1");
		
		//Period 2
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.PeriodPageDetails.titlePeriod2.clear();
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.PeriodPageDetails.titlePeriod2.sendKeys("Period 2");
		Thread.sleep(1000);
		Log.info("Entering Period2 Name");
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.PeriodPageDetails.shortNamePeriod2.clear();
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.PeriodPageDetails.shortNamePeriod2.sendKeys("P2");
		Thread.sleep(1000);
		Log.info("Entering Period2 Short Name");
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.PeriodPageDetails.sortOrderPeriod2.sendKeys("2");
		Thread.sleep(1000);
		Log.info("Entering Period2 Sort Order");
		WebElement startP2Hour = CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.PeriodPageDetails.startHourPeriod2;
		Select selectstartP2Hour = new Select(startP2Hour);
		selectstartP2Hour.selectByValue("9");
		Thread.sleep(1000);
		WebElement startP2Min = CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.PeriodPageDetails.startMinutePeriod2;
		Select selectstartP2Min = new Select(startP2Min);
		selectstartP2Min.selectByValue("40");
		Thread.sleep(1000);
		WebElement startP2Sec = CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.PeriodPageDetails.startSecondPeriod2;
		Select selectstartP2Sec = new Select(startP2Sec);
		selectstartP2Sec.selectByValue("AM");
		Thread.sleep(1000);
		Log.info("Entering Period2 Start Time");
		WebElement endP2Hour = CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.PeriodPageDetails.endHourPeriod2;
		Select selectendP2Hour = new Select(endP2Hour);
		selectendP2Hour.selectByValue("10");
		Thread.sleep(1000);
		WebElement endP2Min = CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.PeriodPageDetails.endMinutePeriod2;
		Select selectendP2Min = new Select(endP2Min);
		selectendP2Min.selectByValue("10");
		Thread.sleep(1000);
		WebElement endP2Sec = CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.PeriodPageDetails.endSecondPeriod2;
		Select selectendP2Sec = new Select(endP2Sec);
		selectendP2Sec.selectByValue("AM");
		Thread.sleep(1000);
		Log.info("Entering Period2 End Time");
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.PeriodPageDetails.usedForAttendancePeriod2.click();
		Thread.sleep(1000);
		Log.info("Clicking on Used For Attendance Checkbox for Period2");
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.PeriodPageDetails.ignoreForSchedulingPeriod2.click();
		Thread.sleep(1000);
		Log.info("Clicking on Ignore For Scheduling Checkbox for Period2");
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.PeriodPageDetails.saveButtonPeriod2.click();
		Thread.sleep(1000);
		Log.info("Clicking on Save Button for Period2");
		
		
		//Grade Level


		CreateSchoolSetupPage.SchoolSetupPageDetails.gradeLevels.click();
		Thread.sleep(1000);
		Log.info("Clicking on Grade Levels Link");
		//Grade Level 1
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.PeriodPageDetails.GradeLabelsPageDetails.titleGradeLevel1.clear();
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.PeriodPageDetails.GradeLabelsPageDetails.titleGradeLevel1.sendKeys("Grade 1");
		Thread.sleep(1000);
		Log.info("Entering Grade1 Name");
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.PeriodPageDetails.GradeLabelsPageDetails.shortNameGradeLevel1.clear();
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.PeriodPageDetails.GradeLabelsPageDetails.shortNameGradeLevel1.sendKeys("G1");
		Thread.sleep(1000);
		Log.info("Entering Grade1 Short Name");
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.PeriodPageDetails.GradeLabelsPageDetails.sortOrdeGradeLevel1.sendKeys("1");
		Thread.sleep(1000);
		Log.info("Entering Grade1 Sort Order");
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.PeriodPageDetails.GradeLabelsPageDetails.saveButtonGradeLevel1.click();
		Thread.sleep(1000);
		Log.info("Clicking on Save Button for Grade1");
		
		//Grade Level 2
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.PeriodPageDetails.GradeLabelsPageDetails.titleGradeLevel2.clear();
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.PeriodPageDetails.GradeLabelsPageDetails.titleGradeLevel2.sendKeys("Grade 2");
		Thread.sleep(1000);
		Log.info("Entering Grade2 Name");
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.PeriodPageDetails.GradeLabelsPageDetails.shortNameGradeLevel2.clear();
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.PeriodPageDetails.GradeLabelsPageDetails.shortNameGradeLevel2.sendKeys("G2");
		Thread.sleep(1000);
		Log.info("Entering Grade2 Short Name");
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.PeriodPageDetails.GradeLabelsPageDetails.sortOrdeGradeLevel2.sendKeys("2");
		Thread.sleep(1000);
		Log.info("Entering Grade2 Sort Order");
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.PeriodPageDetails.GradeLabelsPageDetails.saveButtonGradeLevel2.click();
		Thread.sleep(1000);
		Log.info("Clicking on Save Button for Grade2");
		WebElement nxtGrade = CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.PeriodPageDetails.GradeLabelsPageDetails.nextGradeLevel1;
		Select selectNxtGradeLevel = new Select(nxtGrade);
		selectNxtGradeLevel.selectByVisibleText("Grade 2");
		Thread.sleep(1000);
		Log.info("Select Next Grade Level for Grade1");
		CreateSchoolSetupPage.SchoolSetupPageDetails.CalendarPageDetails.MarkingPeriodPageDetails.RoomPageDetails.PeriodPageDetails.GradeLabelsPageDetails.saveButton.click();
		Thread.sleep(1000);
		Log.info("Clicking on Save Button");
		
		driver.switchTo().defaultContent();
		
	}
}
